# Generated by Django 2.2.2 on 2020-02-18 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha-Hora en que se creo.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora en que se modificó el objeto por última vez.', verbose_name='modified at')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha-Hora en que se creo.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora en que se modificó el objeto por última vez.', verbose_name='modified at')),
                ('id_estado', models.IntegerField(choices=[('Informacion de la entrega', 'Informacion de la entrega'), ('No contesta', 'No contesta'), ('Datos Errados', 'Datos Errados'), ('Cliente pide entrega en almacen', 'Cliente pide entrega en almacen'), ('Zona no cubierta TCL', 'Zona no cubierta TCL'), ('Cliente aplaza entrega', 'Cliente aplaza entrega'), ('Cliente no sabe de la solicitud', 'Cliente no sabe de la solicitud'), ('Almacen se compromete con entrega', 'Almacen se compromete con entrega'), ('Cliente Desiste de la compra', 'Cliente Desiste de la compra')], default='No contesta', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Grabacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha-Hora en que se creo.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora en que se modificó el objeto por última vez.', verbose_name='modified at')),
                ('url', models.URLField()),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LlamadasEntrantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha-Hora en que se creo.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora en que se modificó el objeto por última vez.', verbose_name='modified at')),
                ('estado', models.BooleanField(default=False)),
                ('nombre_solicitante', models.CharField(max_length=50)),
                ('ident_fiscal', models.CharField(max_length=50)),
                ('nombre_destinatario', models.CharField(max_length=50)),
                ('direccion_des_mcia', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('telebox', models.CharField(max_length=50)),
                ('zona_transporte', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=50)),
                ('texto_breve_material', models.CharField(max_length=50)),
                ('documento_ventas', models.CharField(max_length=50)),
                ('entrega', models.CharField(max_length=50)),
                ('num_pedido_cliente', models.CharField(max_length=50)),
                ('cantidad_pedido', models.CharField(max_length=50)),
                ('observaciones_inicial', models.CharField(max_length=255)),
                ('denom_articulos', models.CharField(max_length=50)),
                ('localidad', models.CharField(max_length=50)),
                ('barrio', models.CharField(max_length=50)),
                ('ruta', models.CharField(max_length=50)),
                ('hora_inicio', models.CharField(max_length=50)),
                ('hora_final', models.CharField(max_length=50)),
                ('id_archivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.Archivo')),
                ('id_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroLlamada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha-Hora en que se creo.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora en que se modificó el objeto por última vez.', verbose_name='modified at')),
                ('nombre_contesta', models.CharField(max_length=45, null=True)),
                ('fecha_entrega', models.DateField(auto_now_add=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('realizado', models.BooleanField(default=False, null=True)),
                ('id_estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='file.Estado')),
                ('id_grabacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='file.Grabacion')),
                ('id_llamada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='file.LlamadasEntrantes')),
                ('id_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='usuario.Perfil')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
