# Generated by Django 3.0.4 on 2020-03-15 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrollamada',
            name='id_estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='file.Estado'),
        ),
    ]
