# Generated by Django 2.2.2 on 2020-02-20 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grabacion',
            name='nombre',
            field=models.CharField(default='archivo', max_length=45),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grabacion',
            name='url',
            field=models.FileField(upload_to='audio/mp3'),
        ),
        migrations.AlterField(
            model_name='registrollamada',
            name='fecha_entrega',
            field=models.DateField(null=True),
        ),
    ]
