# Generated by Django 2.2.2 on 2020-02-13 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file', '0002_auto_20200213_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='llamadasentrantes',
            name='id_archivo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='file.Archivo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='llamadasentrantes',
            name='id_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
