# Generated by Django 3.0.4 on 2020-03-26 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_auto_20200315_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrollamada',
            name='precio',
            field=models.PositiveSmallIntegerField(default=50, max_length=510),
        ),
    ]
