# Generated by Django 2.2.2 on 2020-03-03 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_auto_20200303_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='llamadasentrantes',
            old_name='id_archivo',
            new_name='archivo',
        ),
    ]
