# Generated by Django 2.2.2 on 2020-01-20 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_estado_grabacion_registrollamada'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrollamada',
            name='id_llamada',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='file.LlamadasEntrantes'),
            preserve_default=False,
        ),
    ]
