# Generated by Django 2.2.2 on 2020-01-22 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_registrollamada_id_llamada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrollamada',
            name='id_llamada',
        ),
        migrations.AddField(
            model_name='llamadasentrantes',
            name='id_llamada_realizada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='file.RegistroLlamada'),
        ),
    ]
