# Generated by Django 3.0.4 on 2020-03-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_registrollamada_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grabacion',
            name='nombre',
            field=models.CharField(max_length=80),
        ),
    ]
