# Generated by Django 2.2.2 on 2020-02-26 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_auto_20200213_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='grabacion',
            name='nombre',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grabacion',
            name='url',
            field=models.FileField(upload_to='audio/mp3'),
        ),
    ]
