# Generated by Django 2.2.2 on 2020-02-18 17:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_auto_20200213_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivo',
            options={'get_latest_by': 'created', 'ordering': ['-created', '-modified']},
        ),
        migrations.RemoveField(
            model_name='archivo',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='registrollamada',
            name='numero_contesta',
        ),
        migrations.RemoveField(
            model_name='registrollamada',
            name='precio_llamada',
        ),
        migrations.AddField(
            model_name='archivo',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Fecha-Hora en que se creo.', verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='archivo',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora en que se modificó el objeto por última vez.', verbose_name='modified at'),
        ),
    ]
