# Generated by Django 2.2.2 on 2020-02-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0004_auto_20200218_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estado',
            name='id',
        ),
        migrations.AddField(
            model_name='estado',
            name='id_estado',
            field=models.IntegerField(choices=[('Informacion de la entrega', 'Informacion de la entrega'), ('No contesta', 'No contesta'), ('Datos Errados', 'Datos Errados'), ('Cliente pide entrega en almacen', 'Cliente pide entrega en almacen'), ('Zona no cubierta TCL', 'Zona no cubierta TCL'), ('Cliente aplaza entrega', 'Cliente aplaza entrega'), ('Cliente no sabe de la solicitud', 'Cliente no sabe de la solicitud'), ('Almacen se compromete con entrega', 'Almacen se compromete con entrega'), ('Cliente Desiste de la compra', 'Cliente Desiste de la compra')], default='No contesta', primary_key=True, serialize=False),
        ),
    ]
