# Generated by Django 2.2.2 on 2019-12-21 16:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0005_auto_20191211_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='llamadasentrantes',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
