# Generated by Django 2.2.2 on 2020-02-18 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0005_auto_20200218_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrollamada',
            name='id_estado',
        ),
    ]
