# Generated by Django 2.2.2 on 2020-03-02 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0006_remove_llamadasentrantes_id_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grabacion',
            old_name='url',
            new_name='audio',
        ),
    ]
