# Generated by Django 2.2.2 on 2019-11-18 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Grabacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='RegistroLlamada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_contesta', models.CharField(max_length=45)),
                ('fecha_entrega', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('precio_llamada', models.FloatField()),
                ('numero_contesta', models.CharField(max_length=20)),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='llamada.Estado')),
                ('id_grabacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='llamada.Grabacion')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuario.Perfil')),
            ],
        ),
    ]
