# Generated by Django 2.2.2 on 2020-01-15 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_conectado'),
    ]

    operations = [
        migrations.AddField(
            model_name='conectado',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='usuario.Perfil'),
        ),
    ]
