# Generated by Django 2.2.2 on 2019-11-22 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20191121_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='nombre',
        ),
    ]
