# Generated by Django 2.2.2 on 2019-12-10 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20191122_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='cedula',
            field=models.IntegerField(unique=True),
        ),
    ]
