# Generated by Django 2.2.2 on 2019-12-22 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_auto_20191210_0050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='cargo',
        ),
        migrations.AddField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='users/pictures'),
        ),
    ]
