# Generated by Django 2.2.2 on 2019-12-22 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_auto_20191222_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='cedula',
            field=models.IntegerField(default='0'),
        ),
    ]
