# Generated by Django 2.2.2 on 2019-12-30 23:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_auto_20191222_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='celular',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='El numero de telefono debe tener el siguiente formato 1234567890, sin comas ni signos de puntuacion. maximo hasta 10 caracteres', regex='^[1-9]\\d{6,9}$')]),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='celular_telemercadeo',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='El numero de telefono debe tener el siguiente formato 1234567890, sin comas ni signos de puntuacion. maximo hasta 10 caracteres', regex='^[1-9]\\d{6,9}$')]),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefono_fijo',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='El numero de telefono debe tener el siguiente formato 1234567890, sin comas ni signos de puntuacion. maximo hasta 10 caracteres', regex='^[1-9]\\d{6,9}$')]),
        ),
    ]
