# Generated by Django 2.2.2 on 2020-01-08 17:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_auto_20191230_2340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'get_latest_by': 'created', 'ordering': ['-created', '-modified']},
        ),
        migrations.AlterField(
            model_name='perfil',
            name='celular',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='El numero de telefono debe tener el siguiente formato 1234567890, sin comas ni signos de puntuacion. maximo hasta 10 caracteres. mimnimo 7 caracteres', regex='^[1-9]\\d{6,9}$')]),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='celular_telemercadeo',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='El numero de telefono debe tener el siguiente formato 1234567890, sin comas ni signos de puntuacion. maximo hasta 10 caracteres. mimnimo 7 caracteres', regex='^[1-9]\\d{6,9}$')]),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha-Hora en que se creo.', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora en que se modificó el objeto por última vez.', verbose_name='modified at'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefono_fijo',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='El numero de telefono debe tener el siguiente formato 1234567890, sin comas ni signos de puntuacion. maximo hasta 10 caracteres. mimnimo 7 caracteres', regex='^[1-9]\\d{6,9}$')]),
        ),
    ]
